### ISSUE TITLE
num run prepack

### ISSUE THREAD

**Issue by jimstutt** [UofS-CEPHIL/modelcollab#13]
num run prepack returns "gawk: cmd. line:3775: fatal: cannot open file `run' for reading: No such file or directory"

npm run prepack returns "npm ERR! Missing script: "prepack"" although I stalled prepack with npm -g install prepack

**Comment by eRedekopp** [comment]
Is this on the 'main' branch? Unfortunately that branch was left in quite a state and I'm just now getting around to cleaning it up. The "production" branch contains the latest production version. My mistake for not having that set as the default.
